#!/bin/bash
# 1. Let Gemini edit the file
gemini "$1" --file "$2"

# 2. Stage the changes
git add "$2"

# 3. Commit with a message generated by Gemini (optional)
# or just a static message
git commit -m "Gemini: $1"

# 4. Push to your fork (origin)
git push origin Newfeatures
